plugins {
	id 'java'
	id 'jacoco'
	id 'info.solidsoft.pitest' version '1.19.0-rc.3'
}

repositories {
	mavenCentral()
}

dependencies {
	testImplementation platform('org.junit:junit-bom:5.14.4')
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.assertj:assertj-core:3.27.7'
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
		csv.required = false
	}
}

pitest {
	junit5PluginVersion = '1.2.3'
	targetClasses = ['ch.bbw.m450.tictactoe.*']
	outputFormats = ['HTML', 'XML']
	timestampedReports = false
	mutators = ['DEFAULTS']
	mutationThreshold = 80
}
